// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"


// COMPONENT SwitchSetting

lv_obj_t * ui_SwitchSetting_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SwitchSetting;
    cui_SwitchSetting = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_SwitchSetting, 40);
    lv_obj_set_width(cui_SwitchSetting, lv_pct(100));
    lv_obj_set_x(cui_SwitchSetting, 0);
    lv_obj_set_y(cui_SwitchSetting, -26);
    lv_obj_set_align(cui_SwitchSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_SwitchSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_SwitchSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_SwitchSetting, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_SwitchSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_SwitchSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_SwitchSetting, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_SwitchSetting, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_SwitchSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_SwitchSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_SwitchSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_SwitchSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(cui_SwitchSetting, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(cui_SwitchSetting, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(cui_SwitchSetting, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(cui_SwitchSetting, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_Label6;
    cui_Label6 = lv_label_create(cui_SwitchSetting);
    lv_obj_set_width(cui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label6, "Setting");

    lv_obj_t * cui_Switch5;
    cui_Switch5 = lv_switch_create(cui_SwitchSetting);
    lv_obj_set_width(cui_Switch5, 50);
    lv_obj_set_height(cui_Switch5, 25);
    lv_obj_set_align(cui_Switch5, LV_ALIGN_RIGHT_MID);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCHSETTING_NUM);
    children[UI_COMP_SWITCHSETTING_SWITCHSETTING] = cui_SwitchSetting;
    children[UI_COMP_SWITCHSETTING_LABEL6] = cui_Label6;
    children[UI_COMP_SWITCHSETTING_SWITCH5] = cui_Switch5;
    lv_obj_add_event_cb(cui_SwitchSetting, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SwitchSetting, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_SwitchSetting_create_hook(cui_SwitchSetting);
    return cui_SwitchSetting;
}

