// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#ifndef _UI_COMP_SWITCHSETTING_H
#define _UI_COMP_SWITCHSETTING_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SwitchSetting
#define UI_COMP_SWITCHSETTING_SWITCHSETTING 0
#define UI_COMP_SWITCHSETTING_LABEL6 1
#define UI_COMP_SWITCHSETTING_SWITCH5 2
#define _UI_COMP_SWITCHSETTING_NUM 3
lv_obj_t * ui_SwitchSetting_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
