// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ToastMsg_Animation(lv_obj_t * TargetObject, int delay);
void RadWarning_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_HomeScreenArea;
lv_obj_t * ui_PrimaryGuageArea;
lv_obj_t * ui_PrimaryGuage;
lv_obj_t * ui_PrimaryUnit;
lv_obj_t * ui_SecondaryGuageArea;
lv_obj_t * ui_SecondaryGuage;
lv_obj_t * ui_SecondaryUnit;
lv_obj_t * ui_HomeButtonsArea;
void ui_event_ChartNavBtn(lv_event_t * e);
lv_obj_t * ui_ChartNavBtn;
void ui_event_SettingsNavBtn(lv_event_t * e);
lv_obj_t * ui_SettingsNavBtn;
void ui_event_PowerBtn(lv_event_t * e);
lv_obj_t * ui_PowerBtn;
lv_obj_t * ui_TimeDisp;
lv_obj_t * ui_BottomArea;
lv_obj_t * ui_IndicatorArea;
lv_obj_t * ui_BatteryIndicator;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_BatteryGuage;
lv_obj_t * ui_ChargingIcon;
lv_obj_t * ui_BatLabel;
lv_obj_t * ui_ClickerEnableIndicator;
lv_obj_t * ui_AlertIndicator;
lv_obj_t * ui_SleepSampleIndicator;
lv_obj_t * ui_WifiIndicator;
lv_obj_t * ui_BtIndicator;
void ui_event_DoseGuageArea(lv_event_t * e);
lv_obj_t * ui_DoseGuageArea;
lv_obj_t * ui_DoseGuage;
lv_obj_t * ui_DoseUnit;
lv_obj_t * ui_RadRange;
lv_obj_t * ui_PowerOffMsg;
lv_obj_t * ui_PowerOffMsgLabel;
lv_obj_t * ui_RadWarningIcon;
lv_obj_t * ui_NullNavigationSelector;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_SettingsMenu;
lv_obj_t * ui_GeneralSettingsPanel;
void ui_event_GeneralSettingsBtn(lv_event_t * e);
lv_obj_t * ui_GeneralSettingsBtn;
lv_obj_t * ui_GeneralSettingsLabel;
lv_obj_t * ui_MeasurementSettingsPanel;
void ui_event_MeasurementSettingsBtn(lv_event_t * e);
lv_obj_t * ui_MeasurementSettingsBtn;
lv_obj_t * ui_MeasurementSettingsLabel;
lv_obj_t * ui_ConnectivitySettingsPanel;
void ui_event_ConnectivitySettingsBtn(lv_event_t * e);
lv_obj_t * ui_ConnectivitySettingsBtn;
lv_obj_t * ui_ConnectivitySettingsLabel;
lv_obj_t * ui_DisplaySettingsPanel;
void ui_event_DisplaySettingsBtn(lv_event_t * e);
lv_obj_t * ui_DisplaySettingsBtn;
lv_obj_t * ui_DisplaySettingsLabel;
lv_obj_t * ui_AdvancedSettingsPanel;
void ui_event_AdvancedSettingsBtn(lv_event_t * e);
lv_obj_t * ui_AdvancedSettingsBtn;
lv_obj_t * ui_AdvancedSettingsLabel;
lv_obj_t * ui_TopNavBar1;
lv_obj_t * ui_NavBarTitle1;
void ui_event_BackBtn1(lv_event_t * e);
lv_obj_t * ui_BackBtn1;
lv_obj_t * ui_Label11;


// SCREEN: ui_GeneralSettings
void ui_GeneralSettings_screen_init(void);
void ui_event_GeneralSettings(lv_event_t * e);
lv_obj_t * ui_GeneralSettings;
lv_obj_t * ui_GeneralSettingsMenu;
lv_obj_t * ui_ClickerPanel;
lv_obj_t * ui_ClickerLabel;
void ui_event_ClickerSwitch(lv_event_t * e);
lv_obj_t * ui_ClickerSwitch;
lv_obj_t * ui_AlarmPanel;
lv_obj_t * ui_AlarmLabel;
void ui_event_AlarmSwitch(lv_event_t * e);
lv_obj_t * ui_AlarmSwitch;
lv_obj_t * ui_AlarmThrPanel;
lv_obj_t * ui_AlarmThrLabel;
void ui_event_AlarmThresholdInp(lv_event_t * e);
lv_obj_t * ui_AlarmThresholdInp;
lv_obj_t * ui_TimeZonePanel;
lv_obj_t * ui_TimeZoneLabel;
void ui_event_TimeZoneOffsetInpH(lv_event_t * e);
lv_obj_t * ui_TimeZoneOffsetInpH;
void ui_event_TimeZoneOffsetInpM(lv_event_t * e);
lv_obj_t * ui_TimeZoneOffsetInpM;
lv_obj_t * ui_FactoryResetPanel;
void ui_event_FactoryResetBtn(lv_event_t * e);
lv_obj_t * ui_FactoryResetBtn;
lv_obj_t * ui_FactoryResetLabel;
lv_obj_t * ui_TopNavBar2;
lv_obj_t * ui_NavBarTitle2;
void ui_event_BackBtn2(lv_event_t * e);
lv_obj_t * ui_BackBtn2;
lv_obj_t * ui_Label16;
lv_obj_t * ui_ToastMsg;
lv_obj_t * ui_ToastMsgLabel;


// SCREEN: ui_MeasurementSettings
void ui_MeasurementSettings_screen_init(void);
void ui_event_MeasurementSettings(lv_event_t * e);
lv_obj_t * ui_MeasurementSettings;
lv_obj_t * ui_MeasurementSettingsMenu;
lv_obj_t * ui_WindowSizePanel;
lv_obj_t * ui_WindowSizeLabel;
void ui_event_WindowSizeInp(lv_event_t * e);
lv_obj_t * ui_WindowSizeInp;
lv_obj_t * ui_SamplingPeriodPanel;
lv_obj_t * ui_SamplingPeriodLabel;
void ui_event_SamplingPeriodInp(lv_event_t * e);
lv_obj_t * ui_SamplingPeriodInp;
lv_obj_t * ui_WakeToMeasureEnPanel;
lv_obj_t * ui_WakeToMeasureEnLabel;
void ui_event_WakeEnSwitch(lv_event_t * e);
lv_obj_t * ui_WakeEnSwitch;
lv_obj_t * ui_WakeEveryPanel;
lv_obj_t * ui_WakeEveryLabel;
void ui_event_WakeEveryDrop(lv_event_t * e);
lv_obj_t * ui_WakeEveryDrop;
lv_obj_t * ui_WakeSamplePanel;
lv_obj_t * ui_WakeSampleLabel;
void ui_event_WakeSampleDrop(lv_event_t * e);
lv_obj_t * ui_WakeSampleDrop;
lv_obj_t * ui_TopNavBar5;
lv_obj_t * ui_NavBarTitle5;
void ui_event_BackBtn5(lv_event_t * e);
lv_obj_t * ui_BackBtn5;
lv_obj_t * ui_Label14;


// SCREEN: ui_DisplaySettings
void ui_DisplaySettings_screen_init(void);
void ui_event_DisplaySettings(lv_event_t * e);
lv_obj_t * ui_DisplaySettings;
lv_obj_t * ui_DisplaySettingsMenu;
lv_obj_t * ui_BrightnessPanel;
lv_obj_t * ui_BrightnessLabel;
void ui_event_BrightnessSlider(lv_event_t * e);
lv_obj_t * ui_BrightnessSlider;
lv_obj_t * ui_TopNavBar3;
lv_obj_t * ui_NavBarTitle3;
void ui_event_BackBtn3(lv_event_t * e);
lv_obj_t * ui_BackBtn3;
lv_obj_t * ui_Label20;


// SCREEN: ui_History
void ui_History_screen_init(void);
void ui_event_History(lv_event_t * e);
lv_obj_t * ui_History;
lv_obj_t * ui_HistoryScreenArea1;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label37;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label24;
lv_obj_t * ui_HistoryChart;


// SCREEN: ui_AdvancedSettings
void ui_AdvancedSettings_screen_init(void);
void ui_event_AdvancedSettings(lv_event_t * e);
lv_obj_t * ui_AdvancedSettings;
lv_obj_t * ui_AdvancedSettingsMenu;
lv_obj_t * ui_TubeVoltagePanel;
lv_obj_t * ui_TubeVoltageLabel;
void ui_event_TubeVoltageInp(lv_event_t * e);
lv_obj_t * ui_TubeVoltageInp;
lv_obj_t * ui_ConversionRatePanel;
lv_obj_t * ui_ConversionRateLabel;
void ui_event_ConversionRateInp(lv_event_t * e);
lv_obj_t * ui_ConversionRateInp;
lv_obj_t * ui_TopNavBar6;
lv_obj_t * ui_NavBarTitle6;
void ui_event_BackBtn6(lv_event_t * e);
lv_obj_t * ui_BackBtn6;
lv_obj_t * ui_Label29;


// SCREEN: ui_ConnectivitySettings
void ui_ConnectivitySettings_screen_init(void);
void ui_event_ConnectivitySettings(lv_event_t * e);
lv_obj_t * ui_ConnectivitySettings;
lv_obj_t * ui_ConnectivitySettingsMenu;
lv_obj_t * ui_WifiEnPanel;
lv_obj_t * ui_WifiEnLabel;
void ui_event_WifiEnSwitch(lv_event_t * e);
lv_obj_t * ui_WifiEnSwitch;
lv_obj_t * ui_WifiSSIDPanel;
lv_obj_t * ui_WifiSSIDBtn;
lv_obj_t * ui_WifiSSIDLabel;
lv_obj_t * ui_WifiSSIDDisp;
lv_obj_t * ui_WifiRSSIPanel;
lv_obj_t * ui_WifiRSSIBtn;
lv_obj_t * ui_WifiRSSILabel;
lv_obj_t * ui_WifiRSSIDisp;
lv_obj_t * ui_WifiIPPanel;
lv_obj_t * ui_WifiIPBtn;
lv_obj_t * ui_WifiIPLabel;
lv_obj_t * ui_WifiIPDisp;
lv_obj_t * ui_WifiAPEnPanel;
lv_obj_t * ui_WifiAPEnLabel;
void ui_event_WifiAPEnSwitch(lv_event_t * e);
lv_obj_t * ui_WifiAPEnSwitch;
lv_obj_t * ui_MqttEnPanel;
lv_obj_t * ui_MqttEnLabel;
void ui_event_MqttEnSwitch(lv_event_t * e);
lv_obj_t * ui_MqttEnSwitch;
lv_obj_t * ui_MqttStatePanel;
lv_obj_t * ui_MqttStateBtn;
lv_obj_t * ui_MqttStateDisp;
lv_obj_t * ui_TopNavBar4;
lv_obj_t * ui_NavBarTitle4;
void ui_event_BackBtn4(lv_event_t * e);
lv_obj_t * ui_BackBtn4;
lv_obj_t * ui_Label32;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_bell_x[1] = {&ui_img_bell_15x15_png};
const lv_img_dsc_t * ui_imgset_bt_x[1] = {&ui_img_bt_15x15_png};
const lv_img_dsc_t * ui_imgset_gear_icon_x[1] = {&ui_img_gear_icon_20x20_png};
const lv_img_dsc_t * ui_imgset_graph_x[1] = {&ui_img_graph_20x20_png};
const lv_img_dsc_t * ui_imgset_home_x[1] = {&ui_img_home_20x20_png};
const lv_img_dsc_t * ui_imgset_moon_x[1] = {&ui_img_moon_15x15_png};
const lv_img_dsc_t * ui_imgset_power_icon_x[2] = {&ui_img_power_icon_20x20_png, &ui_img_power_icon_25x25_png};
const lv_img_dsc_t * ui_imgset_pwr_icon_x[1] = {&ui_img_pwr_icon_25x25_png};
const lv_img_dsc_t * ui_imgset_radiation_warning_x[1] = {&ui_img_radiation_warning_25x25_png};
const lv_img_dsc_t * ui_imgset_settings_x[1] = {&ui_img_settings_25x25_png};
const lv_img_dsc_t * ui_imgset_volume_high_x[1] = {&ui_img_volume_high_15x15_png};
const lv_img_dsc_t * ui_imgset_volume_xmark_x[1] = {&ui_img_volume_xmark_15x15_png};
const lv_img_dsc_t * ui_imgset_wifi_x[1] = {&ui_img_wifi_15x15_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ToastMsg_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -50);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 0, 50);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 3000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_1);

}
void RadWarning_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 500);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 500);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 500);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_ChartNavBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_History, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_History_screen_init);
    }
}
void ui_event_SettingsNavBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Settings_screen_init);
    }
}
void ui_event_PowerBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        PowerLongPress(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        PowerShortPress(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        PowerReleased(e);
    }
}
void ui_event_DoseGuageArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoseReset(e);
    }
}
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_GeneralSettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_GeneralSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_GeneralSettings_screen_init);
    }
}
void ui_event_MeasurementSettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_MeasurementSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_MeasurementSettings_screen_init);
    }
}
void ui_event_ConnectivitySettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ConnectivitySettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_ConnectivitySettings_screen_init);
    }
}
void ui_event_DisplaySettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DisplaySettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_DisplaySettings_screen_init);
    }
}
void ui_event_AdvancedSettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AdvancedSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_AdvancedSettings_screen_init);
    }
}
void ui_event_BackBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Home_screen_init);
    }
}
void ui_event_GeneralSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_ClickerSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CLickerEnableUpdate(e);
    }
}
void ui_event_AlarmSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AlarmEnableUpdate(e);
    }
}
void ui_event_AlarmThresholdInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        AlarmLimitUpdate(e);
    }
}
void ui_event_TimeZoneOffsetInpH(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        TzOffsetHUpdate(e);
    }
}
void ui_event_TimeZoneOffsetInpM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        TzOffsetMUpdate(e);
    }
}
void ui_event_FactoryResetBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        FactoryReset(e);
        ToastMsg_Animation(ui_ToastMsg, 5);
        _ui_label_set_property(ui_ToastMsgLabel, _UI_LABEL_PROPERTY_TEXT, "Settings have been reset");
    }
}
void ui_event_BackBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Settings_screen_init);
    }
}
void ui_event_MeasurementSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_WindowSizeInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        WindowSizeUpdate(e);
    }
}
void ui_event_SamplingPeriodInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        SamplingPeriodUpdate(e);
    }
}
void ui_event_WakeEnSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WakeEnableUpdate(e);
    }
}
void ui_event_WakeEveryDrop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WakeEveryDropUpdate(e);
    }
}
void ui_event_WakeSampleDrop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WakeSampleDropUpdate(e);
    }
}
void ui_event_BackBtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Settings_screen_init);
    }
}
void ui_event_DisplaySettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ScreenBrightnessUpdate(e);
    }
}
void ui_event_BackBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Settings_screen_init);
    }
}
void ui_event_History(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Home_screen_init);
    }
}
void ui_event_AdvancedSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_TubeVoltageInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        TubeVoltageUpdate(e);
    }
}
void ui_event_ConversionRateInp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ConversionRateUpdate(e);
    }
}
void ui_event_BackBtn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Settings_screen_init);
    }
}
void ui_event_ConnectivitySettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UpdateScreens(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ScreensUnloaded(e);
    }
}
void ui_event_WifiEnSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WifiEnableUpdate(e);
    }
}
void ui_event_WifiAPEnSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WifiAPEnableUpdate(e);
    }
}
void ui_event_MqttEnSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        MqttEnableUpdate(e);
    }
}
void ui_event_BackBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Settings_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
