// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "ui.h"
#include "..\..\src\settings.h"
#include "..\..\src\hardware.h"
#include "..\..\src\gui.h"
#include "..\..\src\geiger.h"
#include "..\..\src\connectivity.h"


void StopAllAnimations(){
	lv_anim_del_all();
}

void CLickerEnableUpdate(lv_event_t *e)
{
	lv_obj_t *sw = lv_event_get_target(e);
	int state = lv_obj_has_state(sw, LV_STATE_CHECKED);
	set_clicker_enabled(state);
}


void UpdateScreens(lv_event_t *e)
{
	update_screens();
}

int window_size_modified = 0;
void WindowSizeUpdate(lv_event_t *e)
{
	lv_obj_t *inp = lv_event_get_target(e);

	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		window_size_modified = 1;
	}
	else if (window_size_modified)
	{
		window_size_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_measurement_window_size(val);
		reset_count_window();
	}
}

int sampling_period_modified = 0;
void SamplingPeriodUpdate(lv_event_t *e)
{
	lv_obj_t *inp = lv_event_get_target(e);

	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		sampling_period_modified = 1;
	}
	else if (sampling_period_modified)
	{
		sampling_period_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_measurement_update_period(val);
		reset_count_window();
	}
}

void ScreenBrightnessUpdate(lv_event_t *e)
{
	lv_obj_t *inp = lv_event_get_target(e);
	int val = lv_slider_get_value(inp);
	set_screen_brightness(val);
	apply_screen_brightness(get_screen_brightness());
}

int pwr_short_pressed = 0;
int pwr_long_pressed = 0;
void CancelPowerOffTimer(lv_timer_t * timer)
{
	pwr_long_pressed = 0;
	lv_obj_add_flag(ui_PowerOffMsg, LV_OBJ_FLAG_HIDDEN);
	lv_timer_del(timer);
}

void PowerLongPress(lv_event_t *e)
{
	pwr_short_pressed = 0;
	pwr_long_pressed = 1;
	lv_obj_clear_flag(ui_PowerOffMsg, LV_OBJ_FLAG_HIDDEN);
	lv_timer_t * timer = lv_timer_create(CancelPowerOffTimer, 3000, NULL);
}

void PowerShortPress(lv_event_t *e)
{
	pwr_short_pressed = 1;
}

void PowerReleased(lv_event_t *e)
{
	if (pwr_short_pressed)
	{
		gui_enable_input(0);
		turn_display_off();
	}else if(pwr_long_pressed){
		StopAllAnimations();
		lv_obj_clean ( lv_scr_act() ); 
		lv_refr_now(NULL);
		enter_deep_sleep();
	}
	pwr_short_pressed = 0;
	pwr_long_pressed = 0;
}

void FactoryReset(lv_event_t * e)
{
	factory_reset();
	UpdateScreens(NULL);
	apply_screen_brightness(get_screen_brightness());
	set_tube_voltage(get_tube_voltage_level());
}

void DoseReset(lv_event_t * e)
{
	reset_dose();
}


void ScreensUnloaded(lv_event_t * e)
{
	StopAllAnimations();
}

void AlarmEnableUpdate(lv_event_t * e)
{
	lv_obj_t *sw = lv_event_get_target(e);
	int state = lv_obj_has_state(sw, LV_STATE_CHECKED);
	set_alarm_enabled(state);
}

int alarm_threshold_modified = 0;
void AlarmLimitUpdate(lv_event_t * e)
{
	lv_obj_t *inp = lv_event_get_target(e);

	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		alarm_threshold_modified = 1;
	}
	else if (alarm_threshold_modified)
	{
		alarm_threshold_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_alarm_threshold(val/100.00);
	}
}

void WakeEnableUpdate(lv_event_t * e)
{
	lv_obj_t *sw = lv_event_get_target(e);
	int state = lv_obj_has_state(sw, LV_STATE_CHECKED);
	set_wake_enabled(state);

}

void WakeEveryDropUpdate(lv_event_t * e)
{
	lv_obj_t *dropdown = lv_event_get_target(e);
	int choice = lv_dropdown_get_selected(dropdown);
	set_wake_every_choice(choice);
}

void WakeSampleDropUpdate(lv_event_t * e)
{
	lv_obj_t *dropdown = lv_event_get_target(e);
	int choice = lv_dropdown_get_selected(dropdown);
	set_wake_sample_choice(choice);
}


int tube_voltage_modified = 0;
void TubeVoltageUpdate(lv_event_t * e)
{
	lv_obj_t *inp = lv_event_get_target(e);
	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		tube_voltage_modified = 1;
	}
	else if (tube_voltage_modified)
	{
		tube_voltage_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_tube_voltage_level(val);
		set_tube_voltage(val);
	}
}

void TubeVoltageLiveUpdate(lv_event_t * e)
{
	lv_obj_t *inp = lv_event_get_target(e);
	int val = lv_spinbox_get_value(inp);
	set_tube_voltage(val);
}

void WifiEnableUpdate(lv_event_t * e)
{
	lv_obj_t *sw = lv_event_get_target(e);
	int state = lv_obj_has_state(sw, LV_STATE_CHECKED);
	if(state){
		enable_wifi();
		set_wifi_enabled(1);
	}else{
		disable_wifi();
		set_wifi_enabled(0);
	}
}

void WifiAPEnableUpdate(lv_event_t * e)
{
	lv_obj_t *sw = lv_event_get_target(e);
	int state = lv_obj_has_state(sw, LV_STATE_CHECKED);
	set_wifi_ap_enabled(state);
	enable_wifi();
}

void MqttEnableUpdate(lv_event_t * e)
{
	lv_obj_t *sw = lv_event_get_target(e);
	int state = lv_obj_has_state(sw, LV_STATE_CHECKED);
	set_mqtt_enabled(state);
	if(state){

	}else{
		mqtt_disconnect();
	}
}

bool tz_offset_h_modified = false;
void TzOffsetHUpdate(lv_event_t * e)
{
	lv_obj_t *inp = lv_event_get_target(e);

	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		tz_offset_h_modified = 1;
	}
	else if (tz_offset_h_modified)
	{
		tz_offset_h_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_timezone_h(val);
	}
}

bool tz_offset_m_modified = false;
void TzOffsetMUpdate(lv_event_t * e)
{
	lv_obj_t *inp = lv_event_get_target(e);

	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		tz_offset_m_modified = 1;
	}
	else if (tz_offset_m_modified)
	{
		tz_offset_m_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_timezone_m(val);
	}
}

int conv_rate_modified = 0;
void ConversionRateUpdate(lv_event_t * e)
{
	lv_obj_t *inp = lv_event_get_target(e);
	if (lv_group_get_editing(lv_obj_get_group(inp)))
	{
		conv_rate_modified = 1;
	}
	else if (conv_rate_modified)
	{
		conv_rate_modified = 0;
		int val = lv_spinbox_get_value(inp);
		set_conversion_rate(val/1000.0);
	}
}
