// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_primary[1] = {0x1B2229};
const ui_theme_variable_t _ui_theme_alpha_primary[1] = {255};

const ui_theme_variable_t _ui_theme_color_navbar[1] = {0x292831};
const ui_theme_variable_t _ui_theme_alpha_navbar[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

