// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"

void ui_AdvancedSettings_screen_init(void)
{
    ui_AdvancedSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AdvancedSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_AdvancedSettings, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_AdvancedSettings);
    lv_obj_set_style_pad_left(ui_AdvancedSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AdvancedSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AdvancedSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AdvancedSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AdvancedSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AdvancedSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdvancedSettingsMenu = lv_obj_create(ui_AdvancedSettings);
    lv_obj_set_height(ui_AdvancedSettingsMenu, 120);
    lv_obj_set_width(ui_AdvancedSettingsMenu, lv_pct(100));
    lv_obj_set_align(ui_AdvancedSettingsMenu, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_AdvancedSettingsMenu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AdvancedSettingsMenu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_AdvancedSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AdvancedSettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AdvancedSettingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AdvancedSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AdvancedSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AdvancedSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AdvancedSettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AdvancedSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AdvancedSettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AdvancedSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TubeVoltagePanel = lv_obj_create(ui_AdvancedSettingsMenu);
    lv_obj_set_height(ui_TubeVoltagePanel, 40);
    lv_obj_set_width(ui_TubeVoltagePanel, lv_pct(100));
    lv_obj_set_x(ui_TubeVoltagePanel, 0);
    lv_obj_set_y(ui_TubeVoltagePanel, -26);
    lv_obj_set_align(ui_TubeVoltagePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TubeVoltagePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TubeVoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TubeVoltagePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_TubeVoltagePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_TubeVoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TubeVoltagePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TubeVoltagePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TubeVoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TubeVoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TubeVoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TubeVoltagePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TubeVoltagePanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_TubeVoltagePanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_TubeVoltagePanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_TubeVoltagePanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_TubeVoltageLabel = lv_label_create(ui_TubeVoltagePanel);
    lv_obj_set_width(ui_TubeVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TubeVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TubeVoltageLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TubeVoltageLabel, "Tube Voltage Level");

    ui_TubeVoltageInp = lv_spinbox_create(ui_TubeVoltagePanel);
    lv_obj_set_width(ui_TubeVoltageInp, 45);
    lv_obj_set_height(ui_TubeVoltageInp, 35);
    lv_obj_set_align(ui_TubeVoltageInp, LV_ALIGN_RIGHT_MID);
    lv_spinbox_set_digit_format(ui_TubeVoltageInp, 3, 0);
    lv_spinbox_set_range(ui_TubeVoltageInp, 1, 255);
    lv_spinbox_set_cursor_pos(ui_TubeVoltageInp, 1 - 1);

    ui_ConversionRatePanel = lv_obj_create(ui_AdvancedSettingsMenu);
    lv_obj_set_height(ui_ConversionRatePanel, 40);
    lv_obj_set_width(ui_ConversionRatePanel, lv_pct(100));
    lv_obj_set_x(ui_ConversionRatePanel, 0);
    lv_obj_set_y(ui_ConversionRatePanel, -26);
    lv_obj_set_align(ui_ConversionRatePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConversionRatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConversionRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ConversionRatePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_ConversionRatePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_ConversionRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConversionRatePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConversionRatePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConversionRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConversionRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConversionRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConversionRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ConversionRatePanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_ConversionRatePanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_ConversionRatePanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_ConversionRatePanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ConversionRateLabel = lv_label_create(ui_ConversionRatePanel);
    lv_obj_set_width(ui_ConversionRateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConversionRateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConversionRateLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ConversionRateLabel, "Conversion Rate");

    ui_ConversionRateInp = lv_spinbox_create(ui_ConversionRatePanel);
    lv_obj_set_width(ui_ConversionRateInp, 84);
    lv_obj_set_height(ui_ConversionRateInp, 35);
    lv_obj_set_align(ui_ConversionRateInp, LV_ALIGN_RIGHT_MID);
    lv_spinbox_set_digit_format(ui_ConversionRateInp, 8, 5);
    lv_spinbox_set_range(ui_ConversionRateInp, 1, 999999);
    lv_spinbox_set_cursor_pos(ui_ConversionRateInp, 1 - 1);

    ui_TopNavBar6 = lv_obj_create(ui_AdvancedSettings);
    lv_obj_set_width(ui_TopNavBar6, 240);
    lv_obj_set_height(ui_TopNavBar6, 15);
    lv_obj_set_align(ui_TopNavBar6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopNavBar6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopNavBar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TopNavBar6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_navbar);
    ui_object_set_themeable_style_property(ui_TopNavBar6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_navbar);
    lv_obj_set_style_border_width(ui_TopNavBar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NavBarTitle6 = lv_label_create(ui_TopNavBar6);
    lv_obj_set_width(ui_NavBarTitle6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NavBarTitle6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NavBarTitle6, 0);
    lv_obj_set_y(ui_NavBarTitle6, -2);
    lv_obj_set_align(ui_NavBarTitle6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NavBarTitle6, "Settings / Advanced");
    lv_obj_set_style_text_font(ui_NavBarTitle6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn6 = lv_btn_create(ui_TopNavBar6);
    lv_obj_set_width(ui_BackBtn6, 12);
    lv_obj_set_height(ui_BackBtn6, 8);
    lv_obj_set_align(ui_BackBtn6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BackBtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackBtn6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_BackBtn6);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "<");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TubeVoltageInp, ui_event_TubeVoltageInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConversionRateInp, ui_event_ConversionRateInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtn6, ui_event_BackBtn6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AdvancedSettings, ui_event_AdvancedSettings, LV_EVENT_ALL, NULL);

}
