// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"

void ui_ConnectivitySettings_screen_init(void)
{
    ui_ConnectivitySettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConnectivitySettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ConnectivitySettings, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                        &ui_ConnectivitySettings);
    lv_obj_set_style_pad_left(ui_ConnectivitySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConnectivitySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConnectivitySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConnectivitySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConnectivitySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConnectivitySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectivitySettingsMenu = lv_obj_create(ui_ConnectivitySettings);
    lv_obj_set_height(ui_ConnectivitySettingsMenu, 120);
    lv_obj_set_width(ui_ConnectivitySettingsMenu, lv_pct(100));
    lv_obj_set_align(ui_ConnectivitySettingsMenu, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ConnectivitySettingsMenu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConnectivitySettingsMenu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_ConnectivitySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConnectivitySettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectivitySettingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConnectivitySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConnectivitySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConnectivitySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConnectivitySettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConnectivitySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConnectivitySettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConnectivitySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnPanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_WifiEnPanel, 40);
    lv_obj_set_width(ui_WifiEnPanel, lv_pct(100));
    lv_obj_set_x(ui_WifiEnPanel, 0);
    lv_obj_set_y(ui_WifiEnPanel, -26);
    lv_obj_set_align(ui_WifiEnPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiEnPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WifiEnPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_WifiEnPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiEnPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiEnPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_WifiEnPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_WifiEnPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_WifiEnPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_WifiEnPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WifiEnLabel = lv_label_create(ui_WifiEnPanel);
    lv_obj_set_width(ui_WifiEnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiEnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiEnLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiEnLabel, "Wi-Fi");

    ui_WifiEnSwitch = lv_switch_create(ui_WifiEnPanel);
    lv_obj_set_width(ui_WifiEnSwitch, 50);
    lv_obj_set_height(ui_WifiEnSwitch, 25);
    lv_obj_set_align(ui_WifiEnSwitch, LV_ALIGN_RIGHT_MID);


    ui_WifiSSIDPanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_WifiSSIDPanel, 40);
    lv_obj_set_width(ui_WifiSSIDPanel, lv_pct(100));
    lv_obj_set_align(ui_WifiSSIDPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiSSIDPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiSSIDPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WifiSSIDPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_WifiSSIDPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_WifiSSIDPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiSSIDPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiSSIDPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiSSIDPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiSSIDPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSSIDBtn = lv_btn_create(ui_WifiSSIDPanel);
    lv_obj_set_width(ui_WifiSSIDBtn, lv_pct(100));
    lv_obj_set_height(ui_WifiSSIDBtn, lv_pct(100));
    lv_obj_set_align(ui_WifiSSIDBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiSSIDBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiSSIDBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiSSIDBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiSSIDBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSSIDBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiSSIDBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiSSIDBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiSSIDBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiSSIDBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSSIDLabel = lv_label_create(ui_WifiSSIDBtn);
    lv_obj_set_width(ui_WifiSSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSSIDLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiSSIDLabel, "Wi-Fi SSID");

    ui_WifiSSIDDisp = lv_label_create(ui_WifiSSIDBtn);
    lv_obj_set_width(ui_WifiSSIDDisp, 120);
    lv_obj_set_height(ui_WifiSSIDDisp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSSIDDisp, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_WifiSSIDDisp, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_WifiSSIDDisp, "");
    lv_obj_set_style_text_align(ui_WifiSSIDDisp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiRSSIPanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_WifiRSSIPanel, 40);
    lv_obj_set_width(ui_WifiRSSIPanel, lv_pct(100));
    lv_obj_set_align(ui_WifiRSSIPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiRSSIPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiRSSIPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WifiRSSIPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_WifiRSSIPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_WifiRSSIPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiRSSIPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiRSSIPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiRSSIPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiRSSIPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiRSSIBtn = lv_btn_create(ui_WifiRSSIPanel);
    lv_obj_set_width(ui_WifiRSSIBtn, lv_pct(100));
    lv_obj_set_height(ui_WifiRSSIBtn, lv_pct(100));
    lv_obj_set_align(ui_WifiRSSIBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiRSSIBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiRSSIBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiRSSIBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiRSSIBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiRSSIBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiRSSIBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiRSSIBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiRSSIBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiRSSIBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiRSSILabel = lv_label_create(ui_WifiRSSIBtn);
    lv_obj_set_width(ui_WifiRSSILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiRSSILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiRSSILabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiRSSILabel, "Signal Strength");

    ui_WifiRSSIDisp = lv_label_create(ui_WifiRSSIBtn);
    lv_obj_set_width(ui_WifiRSSIDisp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiRSSIDisp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiRSSIDisp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_WifiRSSIDisp, "-0dBm");

    ui_WifiIPPanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_WifiIPPanel, 40);
    lv_obj_set_width(ui_WifiIPPanel, lv_pct(100));
    lv_obj_set_align(ui_WifiIPPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiIPPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiIPPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WifiIPPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_WifiIPPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_WifiIPPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiIPPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiIPPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiIPPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiIPPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIPBtn = lv_btn_create(ui_WifiIPPanel);
    lv_obj_set_width(ui_WifiIPBtn, lv_pct(100));
    lv_obj_set_height(ui_WifiIPBtn, lv_pct(100));
    lv_obj_set_align(ui_WifiIPBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiIPBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiIPBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiIPBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiIPBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiIPBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiIPBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiIPBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiIPBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiIPBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIPLabel = lv_label_create(ui_WifiIPBtn);
    lv_obj_set_width(ui_WifiIPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiIPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiIPLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiIPLabel, "IP Address");

    ui_WifiIPDisp = lv_label_create(ui_WifiIPBtn);
    lv_obj_set_width(ui_WifiIPDisp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiIPDisp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiIPDisp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_WifiIPDisp, "");

    ui_WifiAPEnPanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_WifiAPEnPanel, 40);
    lv_obj_set_width(ui_WifiAPEnPanel, lv_pct(100));
    lv_obj_set_x(ui_WifiAPEnPanel, 0);
    lv_obj_set_y(ui_WifiAPEnPanel, -26);
    lv_obj_set_align(ui_WifiAPEnPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiAPEnPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiAPEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WifiAPEnPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_WifiAPEnPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_WifiAPEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WifiAPEnPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WifiAPEnPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WifiAPEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WifiAPEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_WifiAPEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiAPEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_WifiAPEnPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_WifiAPEnPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_WifiAPEnPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_WifiAPEnPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WifiAPEnLabel = lv_label_create(ui_WifiAPEnPanel);
    lv_obj_set_width(ui_WifiAPEnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiAPEnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiAPEnLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiAPEnLabel, "Wi-Fi Access Point");

    ui_WifiAPEnSwitch = lv_switch_create(ui_WifiAPEnPanel);
    lv_obj_set_width(ui_WifiAPEnSwitch, 50);
    lv_obj_set_height(ui_WifiAPEnSwitch, 25);
    lv_obj_set_align(ui_WifiAPEnSwitch, LV_ALIGN_RIGHT_MID);


    ui_MqttEnPanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_MqttEnPanel, 40);
    lv_obj_set_width(ui_MqttEnPanel, lv_pct(100));
    lv_obj_set_x(ui_MqttEnPanel, 0);
    lv_obj_set_y(ui_MqttEnPanel, -26);
    lv_obj_set_align(ui_MqttEnPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MqttEnPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MqttEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MqttEnPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_MqttEnPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_MqttEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MqttEnPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MqttEnPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MqttEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MqttEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_MqttEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MqttEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MqttEnPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_MqttEnPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_MqttEnPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_MqttEnPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_MqttEnLabel = lv_label_create(ui_MqttEnPanel);
    lv_obj_set_width(ui_MqttEnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MqttEnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MqttEnLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MqttEnLabel, "MQTT Telemetry");

    ui_MqttEnSwitch = lv_switch_create(ui_MqttEnPanel);
    lv_obj_set_width(ui_MqttEnSwitch, 50);
    lv_obj_set_height(ui_MqttEnSwitch, 25);
    lv_obj_set_align(ui_MqttEnSwitch, LV_ALIGN_RIGHT_MID);


    ui_MqttStatePanel = lv_obj_create(ui_ConnectivitySettingsMenu);
    lv_obj_set_height(ui_MqttStatePanel, 40);
    lv_obj_set_width(ui_MqttStatePanel, lv_pct(100));
    lv_obj_set_align(ui_MqttStatePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MqttStatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MqttStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MqttStatePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_MqttStatePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_MqttStatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MqttStatePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MqttStatePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MqttStatePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MqttStatePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MqttStateBtn = lv_btn_create(ui_MqttStatePanel);
    lv_obj_set_width(ui_MqttStateBtn, lv_pct(100));
    lv_obj_set_height(ui_MqttStateBtn, lv_pct(100));
    lv_obj_set_align(ui_MqttStateBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttStateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttStateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MqttStateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MqttStateBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MqttStateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MqttStateBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MqttStateBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MqttStateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MqttStateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MqttStateDisp = lv_label_create(ui_MqttStateBtn);
    lv_obj_set_width(ui_MqttStateDisp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MqttStateDisp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MqttStateDisp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MqttStateDisp, "");

    ui_TopNavBar4 = lv_obj_create(ui_ConnectivitySettings);
    lv_obj_set_width(ui_TopNavBar4, 240);
    lv_obj_set_height(ui_TopNavBar4, 15);
    lv_obj_set_align(ui_TopNavBar4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopNavBar4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopNavBar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TopNavBar4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_navbar);
    ui_object_set_themeable_style_property(ui_TopNavBar4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_navbar);
    lv_obj_set_style_border_width(ui_TopNavBar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NavBarTitle4 = lv_label_create(ui_TopNavBar4);
    lv_obj_set_width(ui_NavBarTitle4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NavBarTitle4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NavBarTitle4, 0);
    lv_obj_set_y(ui_NavBarTitle4, -2);
    lv_obj_set_align(ui_NavBarTitle4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NavBarTitle4, "Settings / Connectivity");
    lv_obj_set_style_text_font(ui_NavBarTitle4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn4 = lv_btn_create(ui_TopNavBar4);
    lv_obj_set_width(ui_BackBtn4, 12);
    lv_obj_set_height(ui_BackBtn4, 8);
    lv_obj_set_align(ui_BackBtn4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BackBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackBtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_BackBtn4);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "<");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WifiEnSwitch, ui_event_WifiEnSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiAPEnSwitch, ui_event_WifiAPEnSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttEnSwitch, ui_event_MqttEnSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtn4, ui_event_BackBtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectivitySettings, ui_event_ConnectivitySettings, LV_EVENT_ALL, NULL);

}
