// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"

void ui_DisplaySettings_screen_init(void)
{
    ui_DisplaySettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DisplaySettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_DisplaySettings, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_DisplaySettings);
    lv_obj_set_style_pad_left(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplaySettingsMenu = lv_obj_create(ui_DisplaySettings);
    lv_obj_set_height(ui_DisplaySettingsMenu, 120);
    lv_obj_set_width(ui_DisplaySettingsMenu, lv_pct(100));
    lv_obj_set_align(ui_DisplaySettingsMenu, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_DisplaySettingsMenu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DisplaySettingsMenu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_DisplaySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DisplaySettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplaySettingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DisplaySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DisplaySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DisplaySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DisplaySettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DisplaySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DisplaySettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DisplaySettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessPanel = lv_obj_create(ui_DisplaySettingsMenu);
    lv_obj_set_height(ui_BrightnessPanel, 40);
    lv_obj_set_width(ui_BrightnessPanel, lv_pct(100));
    lv_obj_set_x(ui_BrightnessPanel, 0);
    lv_obj_set_y(ui_BrightnessPanel, -26);
    lv_obj_set_align(ui_BrightnessPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrightnessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrightnessPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_BrightnessPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_BrightnessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BrightnessPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrightnessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BrightnessPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_BrightnessPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_BrightnessPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_BrightnessPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_BrightnessLabel = lv_label_create(ui_BrightnessPanel);
    lv_obj_set_width(ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BrightnessLabel, "Brightness");

    ui_BrightnessSlider = lv_slider_create(ui_BrightnessPanel);
    lv_slider_set_range(ui_BrightnessSlider, 0, 5);
    lv_slider_set_value(ui_BrightnessSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 86);
    lv_obj_set_height(ui_BrightnessSlider, 10);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_RIGHT_MID);


    ui_TopNavBar3 = lv_obj_create(ui_DisplaySettings);
    lv_obj_set_width(ui_TopNavBar3, 240);
    lv_obj_set_height(ui_TopNavBar3, 15);
    lv_obj_set_align(ui_TopNavBar3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopNavBar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopNavBar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TopNavBar3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_navbar);
    ui_object_set_themeable_style_property(ui_TopNavBar3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_navbar);
    lv_obj_set_style_border_width(ui_TopNavBar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NavBarTitle3 = lv_label_create(ui_TopNavBar3);
    lv_obj_set_width(ui_NavBarTitle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NavBarTitle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NavBarTitle3, 0);
    lv_obj_set_y(ui_NavBarTitle3, -2);
    lv_obj_set_align(ui_NavBarTitle3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NavBarTitle3, "Settings / Display");
    lv_obj_set_style_text_font(ui_NavBarTitle3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn3 = lv_btn_create(ui_TopNavBar3);
    lv_obj_set_width(ui_BackBtn3, 12);
    lv_obj_set_height(ui_BackBtn3, 8);
    lv_obj_set_align(ui_BackBtn3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BackBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackBtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_BackBtn3);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "<");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtn3, ui_event_BackBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DisplaySettings, ui_event_DisplaySettings, LV_EVENT_ALL, NULL);

}
