// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"

void ui_GeneralSettings_screen_init(void)
{
    ui_GeneralSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GeneralSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_GeneralSettings, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_GeneralSettings);
    lv_obj_set_style_pad_left(ui_GeneralSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GeneralSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GeneralSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GeneralSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_GeneralSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_GeneralSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GeneralSettingsMenu = lv_obj_create(ui_GeneralSettings);
    lv_obj_set_height(ui_GeneralSettingsMenu, 120);
    lv_obj_set_width(ui_GeneralSettingsMenu, lv_pct(100));
    lv_obj_set_align(ui_GeneralSettingsMenu, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_GeneralSettingsMenu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GeneralSettingsMenu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_GeneralSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GeneralSettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GeneralSettingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GeneralSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GeneralSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GeneralSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GeneralSettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GeneralSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_GeneralSettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_GeneralSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClickerPanel = lv_obj_create(ui_GeneralSettingsMenu);
    lv_obj_set_height(ui_ClickerPanel, 40);
    lv_obj_set_width(ui_ClickerPanel, lv_pct(100));
    lv_obj_set_x(ui_ClickerPanel, 0);
    lv_obj_set_y(ui_ClickerPanel, -26);
    lv_obj_set_align(ui_ClickerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ClickerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ClickerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ClickerPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_ClickerPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_ClickerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ClickerPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ClickerPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ClickerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ClickerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ClickerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ClickerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ClickerPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_ClickerPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_ClickerPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_ClickerPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ClickerLabel = lv_label_create(ui_ClickerPanel);
    lv_obj_set_width(ui_ClickerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClickerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ClickerLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ClickerLabel, "Clicker");

    ui_ClickerSwitch = lv_switch_create(ui_ClickerPanel);
    lv_obj_set_width(ui_ClickerSwitch, 50);
    lv_obj_set_height(ui_ClickerSwitch, 25);
    lv_obj_set_align(ui_ClickerSwitch, LV_ALIGN_RIGHT_MID);


    ui_AlarmPanel = lv_obj_create(ui_GeneralSettingsMenu);
    lv_obj_set_height(ui_AlarmPanel, 40);
    lv_obj_set_width(ui_AlarmPanel, lv_pct(100));
    lv_obj_set_x(ui_AlarmPanel, 0);
    lv_obj_set_y(ui_AlarmPanel, -26);
    lv_obj_set_align(ui_AlarmPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AlarmPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AlarmPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_AlarmPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_AlarmPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AlarmPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AlarmPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AlarmPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AlarmPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AlarmPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AlarmPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_AlarmPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_AlarmPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_AlarmPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_AlarmPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_AlarmLabel = lv_label_create(ui_AlarmPanel);
    lv_obj_set_width(ui_AlarmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AlarmLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmLabel, "Alarm");

    ui_AlarmSwitch = lv_switch_create(ui_AlarmPanel);
    lv_obj_set_width(ui_AlarmSwitch, 50);
    lv_obj_set_height(ui_AlarmSwitch, 25);
    lv_obj_set_align(ui_AlarmSwitch, LV_ALIGN_RIGHT_MID);


    ui_AlarmThrPanel = lv_obj_create(ui_GeneralSettingsMenu);
    lv_obj_set_height(ui_AlarmThrPanel, 40);
    lv_obj_set_width(ui_AlarmThrPanel, lv_pct(100));
    lv_obj_set_x(ui_AlarmThrPanel, 0);
    lv_obj_set_y(ui_AlarmThrPanel, -26);
    lv_obj_set_align(ui_AlarmThrPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AlarmThrPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmThrPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AlarmThrPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_AlarmThrPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_AlarmThrPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AlarmThrPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AlarmThrPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AlarmThrPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AlarmThrPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AlarmThrPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AlarmThrPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_AlarmThrPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_AlarmThrPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_AlarmThrPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_AlarmThrPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_AlarmThrLabel = lv_label_create(ui_AlarmThrPanel);
    lv_obj_set_width(ui_AlarmThrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmThrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AlarmThrLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AlarmThrLabel, "Alarm Thr. (uSv/h)");

    ui_AlarmThresholdInp = lv_spinbox_create(ui_AlarmThrPanel);
    lv_obj_set_width(ui_AlarmThresholdInp, 84);
    lv_obj_set_height(ui_AlarmThresholdInp, 35);
    lv_obj_set_align(ui_AlarmThresholdInp, LV_ALIGN_RIGHT_MID);
    lv_spinbox_set_digit_format(ui_AlarmThresholdInp, 8, 6);
    lv_spinbox_set_range(ui_AlarmThresholdInp, 1, 99999999);
    lv_spinbox_set_cursor_pos(ui_AlarmThresholdInp, 1 - 1);

    ui_TimeZonePanel = lv_obj_create(ui_GeneralSettingsMenu);
    lv_obj_set_height(ui_TimeZonePanel, 40);
    lv_obj_set_width(ui_TimeZonePanel, lv_pct(100));
    lv_obj_set_x(ui_TimeZonePanel, 0);
    lv_obj_set_y(ui_TimeZonePanel, -26);
    lv_obj_set_align(ui_TimeZonePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeZonePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeZonePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeZonePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_TimeZonePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_TimeZonePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TimeZonePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TimeZonePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TimeZonePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TimeZonePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TimeZonePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TimeZonePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TimeZonePanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_TimeZonePanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_TimeZonePanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_TimeZonePanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_TimeZoneLabel = lv_label_create(ui_TimeZonePanel);
    lv_obj_set_width(ui_TimeZoneLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeZoneLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeZoneLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TimeZoneLabel, "Time Zone");

    ui_TimeZoneOffsetInpH = lv_spinbox_create(ui_TimeZonePanel);
    lv_obj_set_width(ui_TimeZoneOffsetInpH, 46);
    lv_obj_set_height(ui_TimeZoneOffsetInpH, 35);
    lv_obj_set_x(ui_TimeZoneOffsetInpH, -50);
    lv_obj_set_y(ui_TimeZoneOffsetInpH, 0);
    lv_obj_set_align(ui_TimeZoneOffsetInpH, LV_ALIGN_RIGHT_MID);
    lv_spinbox_set_digit_format(ui_TimeZoneOffsetInpH, 2, 2);
    lv_spinbox_set_range(ui_TimeZoneOffsetInpH, -12, 14);
    lv_spinbox_set_cursor_pos(ui_TimeZoneOffsetInpH, 1 - 1);

    ui_TimeZoneOffsetInpM = lv_spinbox_create(ui_TimeZonePanel);
    lv_obj_set_width(ui_TimeZoneOffsetInpM, 46);
    lv_obj_set_height(ui_TimeZoneOffsetInpM, 35);
    lv_obj_set_align(ui_TimeZoneOffsetInpM, LV_ALIGN_RIGHT_MID);
    lv_spinbox_set_digit_format(ui_TimeZoneOffsetInpM, 2, 2);
    lv_spinbox_set_range(ui_TimeZoneOffsetInpM, 0, 59);
    lv_spinbox_set_cursor_pos(ui_TimeZoneOffsetInpM, 1 - 1);

    ui_FactoryResetPanel = lv_obj_create(ui_GeneralSettingsMenu);
    lv_obj_set_height(ui_FactoryResetPanel, 40);
    lv_obj_set_width(ui_FactoryResetPanel, lv_pct(100));
    lv_obj_set_x(ui_FactoryResetPanel, 0);
    lv_obj_set_y(ui_FactoryResetPanel, -26);
    lv_obj_set_align(ui_FactoryResetPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FactoryResetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FactoryResetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FactoryResetPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_FactoryResetPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_FactoryResetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FactoryResetPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FactoryResetPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FactoryResetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FactoryResetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_FactoryResetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FactoryResetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FactoryResetPanel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_FactoryResetPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_FactoryResetPanel, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_FactoryResetPanel, -1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_FactoryResetBtn = lv_btn_create(ui_FactoryResetPanel);
    lv_obj_set_width(ui_FactoryResetBtn, 165);
    lv_obj_set_height(ui_FactoryResetBtn, 32);
    lv_obj_set_align(ui_FactoryResetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FactoryResetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FactoryResetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FactoryResetBtn, lv_color_hex(0x710000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FactoryResetBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FactoryResetLabel = lv_label_create(ui_FactoryResetBtn);
    lv_obj_set_width(ui_FactoryResetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FactoryResetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FactoryResetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FactoryResetLabel, "Factory Reset (Hold)");

    ui_TopNavBar2 = lv_obj_create(ui_GeneralSettings);
    lv_obj_set_width(ui_TopNavBar2, 240);
    lv_obj_set_height(ui_TopNavBar2, 15);
    lv_obj_set_align(ui_TopNavBar2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopNavBar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopNavBar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TopNavBar2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_navbar);
    ui_object_set_themeable_style_property(ui_TopNavBar2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_navbar);
    lv_obj_set_style_border_width(ui_TopNavBar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NavBarTitle2 = lv_label_create(ui_TopNavBar2);
    lv_obj_set_width(ui_NavBarTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NavBarTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NavBarTitle2, 0);
    lv_obj_set_y(ui_NavBarTitle2, -2);
    lv_obj_set_align(ui_NavBarTitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NavBarTitle2, "Settings / General");
    lv_obj_set_style_text_font(ui_NavBarTitle2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn2 = lv_btn_create(ui_TopNavBar2);
    lv_obj_set_width(ui_BackBtn2, 12);
    lv_obj_set_height(ui_BackBtn2, 8);
    lv_obj_set_align(ui_BackBtn2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BackBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackBtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_BackBtn2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "<");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToastMsg = lv_obj_create(ui_GeneralSettings);
    lv_obj_set_height(ui_ToastMsg, 31);
    lv_obj_set_width(ui_ToastMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ToastMsg, 0);
    lv_obj_set_y(ui_ToastMsg, 40);
    lv_obj_set_align(ui_ToastMsg, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ToastMsg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ToastMsgLabel = lv_label_create(ui_ToastMsg);
    lv_obj_set_width(ui_ToastMsgLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToastMsgLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToastMsgLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToastMsgLabel, "");

    lv_obj_add_event_cb(ui_ClickerSwitch, ui_event_ClickerSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmSwitch, ui_event_AlarmSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AlarmThresholdInp, ui_event_AlarmThresholdInp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeZoneOffsetInpH, ui_event_TimeZoneOffsetInpH, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeZoneOffsetInpM, ui_event_TimeZoneOffsetInpM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FactoryResetBtn, ui_event_FactoryResetBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtn2, ui_event_BackBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GeneralSettings, ui_event_GeneralSettings, LV_EVENT_ALL, NULL);

}
