// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"

void ui_History_screen_init(void)
{
    ui_History = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_History, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_History, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_History);

    ui_HistoryScreenArea1 = lv_obj_create(ui_History);
    lv_obj_remove_style_all(ui_HistoryScreenArea1);
    lv_obj_set_width(ui_HistoryScreenArea1, 240);
    lv_obj_set_height(ui_HistoryScreenArea1, 135);
    lv_obj_set_align(ui_HistoryScreenArea1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HistoryScreenArea1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HistoryScreenArea1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HistoryScreenArea1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel20 = lv_obj_create(ui_HistoryScreenArea1);
    lv_obj_set_width(ui_Panel20, 240);
    lv_obj_set_height(ui_Panel20, 15);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_navbar);
    ui_object_set_themeable_style_property(ui_Panel20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_navbar);
    lv_obj_set_style_border_width(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 0);
    lv_obj_set_y(ui_Label37, -2);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "History graph");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_btn_create(ui_Panel20);
    lv_obj_set_width(ui_Button21, 12);
    lv_obj_set_height(ui_Button21, 8);
    lv_obj_set_align(ui_Button21, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Button21);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "<");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HistoryChart = lv_chart_create(ui_History);
    lv_obj_set_width(ui_HistoryChart, 200);
    lv_obj_set_height(ui_HistoryChart, 100);
    lv_obj_set_x(ui_HistoryChart, 13);
    lv_obj_set_y(ui_HistoryChart, 3);
    lv_obj_set_align(ui_HistoryChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_HistoryChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_HistoryChart, 20);
    lv_chart_set_axis_tick(ui_HistoryChart, LV_CHART_AXIS_PRIMARY_X, 3, 0, 10, 2, false, 50);
    lv_chart_set_axis_tick(ui_HistoryChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 10);
    lv_chart_set_axis_tick(ui_HistoryChart, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);
    lv_chart_series_t * ui_HistoryChart_series_1 = lv_chart_add_series(ui_HistoryChart, lv_color_hex(0x808080),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_HistoryChart_series_1_array[] = { 1 };
    lv_chart_set_ext_y_array(ui_HistoryChart, ui_HistoryChart_series_1, ui_HistoryChart_series_1_array);
    lv_obj_set_style_radius(ui_HistoryChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HistoryChart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HistoryChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_set_style_line_color(ui_HistoryChart, lv_color_hex(0x808080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_HistoryChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HistoryChart, &lv_font_montserrat_10, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_History, ui_event_History, LV_EVENT_ALL, NULL);

}
