// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRad

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Settings, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Settings);
    lv_obj_set_style_pad_left(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsMenu = lv_obj_create(ui_Settings);
    lv_obj_set_height(ui_SettingsMenu, 120);
    lv_obj_set_width(ui_SettingsMenu, lv_pct(100));
    lv_obj_set_align(ui_SettingsMenu, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_SettingsMenu, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsMenu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_SettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GeneralSettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_height(ui_GeneralSettingsPanel, 40);
    lv_obj_set_width(ui_GeneralSettingsPanel, lv_pct(100));
    lv_obj_set_align(ui_GeneralSettingsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GeneralSettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GeneralSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GeneralSettingsPanel, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GeneralSettingsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GeneralSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GeneralSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GeneralSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GeneralSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GeneralSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GeneralSettingsBtn = lv_btn_create(ui_GeneralSettingsPanel);
    lv_obj_set_width(ui_GeneralSettingsBtn, lv_pct(100));
    lv_obj_set_height(ui_GeneralSettingsBtn, lv_pct(100));
    lv_obj_set_align(ui_GeneralSettingsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GeneralSettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GeneralSettingsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GeneralSettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_GeneralSettingsBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_GeneralSettingsBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);

    ui_GeneralSettingsLabel = lv_label_create(ui_GeneralSettingsBtn);
    lv_obj_set_width(ui_GeneralSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GeneralSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GeneralSettingsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_GeneralSettingsLabel, "General");

    ui_MeasurementSettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_height(ui_MeasurementSettingsPanel, 40);
    lv_obj_set_width(ui_MeasurementSettingsPanel, lv_pct(100));
    lv_obj_set_align(ui_MeasurementSettingsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MeasurementSettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MeasurementSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MeasurementSettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_MeasurementSettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_MeasurementSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MeasurementSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MeasurementSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MeasurementSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MeasurementSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasurementSettingsBtn = lv_btn_create(ui_MeasurementSettingsPanel);
    lv_obj_set_width(ui_MeasurementSettingsBtn, lv_pct(100));
    lv_obj_set_height(ui_MeasurementSettingsBtn, lv_pct(100));
    lv_obj_set_align(ui_MeasurementSettingsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeasurementSettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeasurementSettingsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MeasurementSettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MeasurementSettingsBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_MeasurementSettingsBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);

    ui_MeasurementSettingsLabel = lv_label_create(ui_MeasurementSettingsBtn);
    lv_obj_set_width(ui_MeasurementSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasurementSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeasurementSettingsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MeasurementSettingsLabel, "Measurements");

    ui_ConnectivitySettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_height(ui_ConnectivitySettingsPanel, 40);
    lv_obj_set_width(ui_ConnectivitySettingsPanel, lv_pct(100));
    lv_obj_set_align(ui_ConnectivitySettingsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConnectivitySettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConnectivitySettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ConnectivitySettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_ConnectivitySettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_ConnectivitySettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConnectivitySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConnectivitySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConnectivitySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConnectivitySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectivitySettingsBtn = lv_btn_create(ui_ConnectivitySettingsPanel);
    lv_obj_set_width(ui_ConnectivitySettingsBtn, lv_pct(100));
    lv_obj_set_height(ui_ConnectivitySettingsBtn, lv_pct(100));
    lv_obj_set_align(ui_ConnectivitySettingsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectivitySettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectivitySettingsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConnectivitySettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConnectivitySettingsBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectivitySettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectivitySettingsLabel = lv_label_create(ui_ConnectivitySettingsBtn);
    lv_obj_set_width(ui_ConnectivitySettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectivitySettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectivitySettingsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ConnectivitySettingsLabel, "Connectivity");

    ui_DisplaySettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_height(ui_DisplaySettingsPanel, 40);
    lv_obj_set_width(ui_DisplaySettingsPanel, lv_pct(100));
    lv_obj_set_align(ui_DisplaySettingsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DisplaySettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DisplaySettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_DisplaySettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_DisplaySettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_DisplaySettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DisplaySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DisplaySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DisplaySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DisplaySettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplaySettingsBtn = lv_btn_create(ui_DisplaySettingsPanel);
    lv_obj_set_width(ui_DisplaySettingsBtn, lv_pct(100));
    lv_obj_set_height(ui_DisplaySettingsBtn, lv_pct(100));
    lv_obj_set_align(ui_DisplaySettingsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisplaySettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DisplaySettingsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DisplaySettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DisplaySettingsBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplaySettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplaySettingsLabel = lv_label_create(ui_DisplaySettingsBtn);
    lv_obj_set_width(ui_DisplaySettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisplaySettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DisplaySettingsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DisplaySettingsLabel, "Display");

    ui_AdvancedSettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_height(ui_AdvancedSettingsPanel, 40);
    lv_obj_set_width(ui_AdvancedSettingsPanel, lv_pct(100));
    lv_obj_set_align(ui_AdvancedSettingsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AdvancedSettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AdvancedSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AdvancedSettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_primary);
    ui_object_set_themeable_style_property(ui_AdvancedSettingsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_primary);
    lv_obj_set_style_border_width(ui_AdvancedSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AdvancedSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AdvancedSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AdvancedSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AdvancedSettingsPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdvancedSettingsBtn = lv_btn_create(ui_AdvancedSettingsPanel);
    lv_obj_set_width(ui_AdvancedSettingsBtn, lv_pct(100));
    lv_obj_set_height(ui_AdvancedSettingsBtn, lv_pct(100));
    lv_obj_set_align(ui_AdvancedSettingsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AdvancedSettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AdvancedSettingsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AdvancedSettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AdvancedSettingsBtn, lv_color_hex(0x1B2229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AdvancedSettingsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdvancedSettingsLabel = lv_label_create(ui_AdvancedSettingsBtn);
    lv_obj_set_width(ui_AdvancedSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdvancedSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AdvancedSettingsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AdvancedSettingsLabel, "Advanced");

    ui_TopNavBar1 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_TopNavBar1, 240);
    lv_obj_set_height(ui_TopNavBar1, 15);
    lv_obj_set_align(ui_TopNavBar1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopNavBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopNavBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TopNavBar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_navbar);
    ui_object_set_themeable_style_property(ui_TopNavBar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_navbar);
    lv_obj_set_style_border_width(ui_TopNavBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NavBarTitle1 = lv_label_create(ui_TopNavBar1);
    lv_obj_set_width(ui_NavBarTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NavBarTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NavBarTitle1, 0);
    lv_obj_set_y(ui_NavBarTitle1, -2);
    lv_obj_set_align(ui_NavBarTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NavBarTitle1, "Settings");
    lv_obj_set_style_text_font(ui_NavBarTitle1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn1 = lv_btn_create(ui_TopNavBar1);
    lv_obj_set_width(ui_BackBtn1, 12);
    lv_obj_set_height(ui_BackBtn1, 8);
    lv_obj_set_align(ui_BackBtn1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BackBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_BackBtn1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "<");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GeneralSettingsBtn, ui_event_GeneralSettingsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeasurementSettingsBtn, ui_event_MeasurementSettingsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectivitySettingsBtn, ui_event_ConnectivitySettingsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DisplaySettingsBtn, ui_event_DisplaySettingsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AdvancedSettingsBtn, ui_event_AdvancedSettingsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackBtn1, ui_event_BackBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
